### ISSUE TITLE
Not writing new data to file

### ISSUE THREAD

**Issue by thunder175** [Tantares/ProjectManager#2]
I'm having issues with the most current version and 1.3.1. The numbering only works for one game play session, that is, numbering is reset to 0 after i restart or reload the game. If I remember where I left off and edit the file manually after closing KSP, the sequencing starts again as would be expected. It appears that the plug in is not writing any new data to the file created in the save folder, although it is updating the last modified time stamp.

**Comment by Tantares** [comment]
Unfortunately no compatibility can be offered for KSP 1.3.1 on the current version (Compiled for KSP 1.7+)
Apologies.
